# Generated by Django 4.2.1 on 2023-06-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipe_id_alter_recipe_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='favorite_user_recipe',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='shoppingcart_user_recipe',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='owner',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='favorite_user_recipe'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='shoppingcart_user_recipe'),
        ),
    ]
